services:
  - type: web
    name: wildlife-injury-inference
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /system-status
    envVars:
      - key: DISABLE_LIVE_CAMERA
        value: "1"
      - key: DISABLE_VIDEO
        value: "1"
